// src/pages/TermsOfService.jsx
import { useNavigate } from "react-router-dom";
import { ArrowLeft, FileText } from "lucide-react";

export default function TermsOfService() {
  const navigate = useNavigate();
  return (
    <div className="min-h-screen bg-white pb-24">
      <div className="container mx-auto px-4 py-6 max-w-2xl">
        <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-gray-500 hover:text-gray-700 mb-6 text-sm">
          <ArrowLeft className="w-4 h-4" /> Back
        </button>

        <div className="flex items-center gap-3 mb-8">
          <FileText className="w-8 h-8 text-blue-600" />
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Terms of Service</h1>
            <p className="text-gray-400 text-sm">Last updated: May 2026</p>
          </div>
        </div>

        <div className="prose prose-sm max-w-none text-gray-700 space-y-6">
          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By using BasketSaver, you agree to these Terms of Service. If you do not agree, please do not use the app.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">2. Price Information Disclaimer</h2>
            <p>BasketSaver provides grocery price comparisons for informational purposes only. Prices shown are either real-time data from store APIs or algorithm-based estimates.</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Store prices are sourced from available retail data and are accurate at time of display.</li>
              <li>Estimated prices for other stores are generated by our algorithm and may differ from actual in-store prices by up to 15%.</li>
              <li>BasketSaver is not responsible for price discrepancies between the app and actual store prices.</li>
              <li>Always verify prices in-store before making purchasing decisions.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">3. User Accounts</h2>
            <p>You are responsible for maintaining the security of your account. You must provide accurate information when creating an account. You may not use another person's account.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">4. Acceptable Use</h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Use the app for any unlawful purpose</li>
              <li>Attempt to scrape or automate data collection</li>
              <li>Interfere with the app's functionality</li>
              <li>Submit false or misleading receipt data</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">5. Data Contribution</h2>
            <p>When you scan receipts or contribute pricing data, you grant BasketSaver a license to use that anonymized data to improve our pricing algorithm and regional trend analysis.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">6. Limitation of Liability</h2>
            <p>BasketSaver is provided "as is" without warranties. We are not liable for any losses arising from reliance on price information displayed in the app.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">7. Changes to Terms</h2>
            <p>We may update these terms at any time. Continued use of the app after changes constitutes acceptance of the new terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-bold text-gray-900 mb-2">8. Contact</h2>
            <p>Questions? Contact us at <span className="text-blue-600">splainbryan@gmail.com</span></p>
          </section>
        </div>
      </div>
    </div>
  );
}
